### PR TITLE
New Feature: Application config group

### PR DESCRIPTION
**Pull request by GLYASAI**
make config group work: convert config items into environment variables in kubernetes object

### CODE REVIEW

**Comment by barnettZQG** [comment]
application config group should implement by `Secret`.

**Comment by GLYASAI** [comment]
@barnettZQG fixed

**Comment by barnettZQG** [comment]
The plugin container does not inject config env? The plugin container should be consistent with the main container.

**Comment by barnettZQG** [comment]
@GLYASAI

**Comment by barnettZQG** [comment]
Provide effect screenshot

**Comment by GLYASAI** [comment]
It's [here](https://github.com/goodrain/rainbond/pull/855/files#diff-5edc24e80dd276eca81d4ec1825743c7ec14afd5f729b72194df764da4d5b34aR215)

**Comment by GLYASAI** [comment]
image
@barnettZQG

**Comment by GLYASAI** [comment]
> The plugin container does not inject config env? The plugin container should be consistent with the main container.

ok

**Review by barnettZQG — APPROVED** [review]

**Pull request merged**
